### ISSUE TITLE
请问为何Mac上每次启动项目会把我的虚拟机打开？这个可以更改设置吗

### ISSUE THREAD

**Issue by ByWhiter** [legoflow/legoflow#1]
貌似是关联了虚拟机的浏览器，但我想设置成Mac的浏览器启动，但是找不到设置项？请问可以修改吗
![awavsdywle](https://user-images.githubusercontent.com/13621465/27018126-849bf5f6-4f60-11e7-8a82-38686d5d65cb.gif)

**Comment by lilijialiang** [comment]
请问使用哪个模拟器呢？

我们这边测试一下，发现这个 BUG 的话，发了发个公共补丁就可以修复的啦

**Comment by ByWhiter** [comment]
好的谢谢，有设置指定浏览器启动最好呢

**Comment by lilijialiang** [comment]
我们这边测试了一下，这样的情况出现，应该是 工作流 打开浏览器是使用 browser-sync 的 browser 设置 ，估计而你的 Parallels 配置了 默认 Chrome 指向了 虚拟机 window 上的 Chrome。

修改方案是 设置 mac 下的 Chrome 为默认，教程如下
https://forum.parallels.com/threads/parallels-changes-default-browser-chrome-mac-to-chrome-windows.285561/

如果还有问题的话，可以详细 加一下 Q 群 ( 457756220 ) 交流哈

**Comment by ByWhiter** [comment]
谢谢已解决,在web那个选项里，选择在Mac打开
<img width="668" alt="windows 7 - parallels desktop at 1 15 58" src="https://user-images.githubusercontent.com/13621465/27020255-1b7a3fe4-4f72-11e7-8ebd-c9de5b1a7da0.png">

**Comment by lilijialiang** [comment]
🎉🎉
