### ISSUE TITLE
开发环境在win8下启动很慢，大概需要20分钟

### ISSUE THREAD

**Issue by fengweiqi** [legoflow/legoflow#11]
如果我用的是webpack自己配置的，启动就1，2秒，咋回事

**Comment by lilijialiang** [comment]
@fengweiqi 我们在多台 Windows 7 / 8 / 10 测试过，低配的机子，新建的项目 都能在半分钟内启动。

启动时间除了跟机子配置之外，还跟项目的大小程度（ 其中项目越大编译的文件越多 ）有关系。

另外现今的 Webpack 版本是 3.x，比内置的版本要高很多，优化了各项功能。

或许提供更多的参数，让我们了解情况，再能有详细的测试结果。
