### ISSUE TITLE
能不能增加一下创建iview项目

### ISSUE THREAD

**Issue by yohann-git** [legoflow/legoflow#14]
用iview比较多

**Comment by lilijialiang** [comment]
第三方框架，可以通过使用 vue 项目初始化后，外链的形式引入 iview 即可。

我们后面版本会支持自定义初始化项目脚手架，这样每个人都能定制一些自己需要的默认创建项目类型。

**Comment by lilijialiang** [comment]
客户端版本 **v2.0.0-beta.4** 新增 **[Wiki-自定义项目类型](https://legoflow.com/wiki/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B9%E7%9B%AE%E7%B1%BB%E5%9E%8B)**
