### ISSUE TITLE
mobile项目 toRem 尺寸换算疑问？

### ISSUE THREAD

**Issue by Lenny-Hu** [legoflow/legoflow#16]
2.0beta7生成的移动项目，切假设设计稿为750，有一宽度为100px（直接ps量的100px），使用ToRem函数处理单位，那么当浏览器视窗大于等于750时（已添加750断点查询），该元素在开发者工具中的宽度尺寸正常应该是100px，但实际上不是100px。

torem函数的内部实现为 px / （750 /16 / 1rem）,  难道不应该是 0.01rem  * px? 所以 100px，正好是1rem，当窗口大于等于750时，元素尺寸正好是100px。

**Comment by lijialiang** [comment]
可以不使用 ToRem 函数处理，100 px 可以直接写成 1 rem，10 px 写成 0.1 rem

750 px 设计稿实际 px 单位 除以 100 即可为 rem 单位

**Comment by Lenny-Hu** [comment]
@lijialiang 好的。

**Comment by lijialiang** [comment]
另外因为现在 Node 环境很早已趋向稳定，以及 CI 构建流程的成熟，我们后面逐渐放弃对客户端的支持，如果有需要的话，可以 fork 去实现你想要的功能。

**Comment by Lenny-Hu** [comment]
> 另外因为现在 Node 环境很早已趋向稳定，以及 CI 构建流程的成熟，我们后面逐渐放弃对客户端的支持，如果有需要的话，可以 fork 去实现你想要的功能。

好的，谢谢
