### ISSUE TITLE
多页面公共模板

### ISSUE THREAD

**Issue by XIAOGUIGUI** [legoflow/legoflow#2]
请问pc多页面的公共页面模板怎么处理？

**Comment by lilijialiang** [comment]
请问有没有接触过 EJS ？在 src 下创建 ejs 文件夹 放置 ejs 文件，ejs 可以 include 一些公共模板。ejs 会编译出 html 到 src 路径下。文档 https://github.com/legoflow/legoflow/wiki/2.3.-EJS编译
