### ISSUE TITLE
官网顶部的导航栏里的链接，target都是_bank，好像没有这种写法吧

### ISSUE THREAD

**Issue by maoqxxmm** [legoflow/legoflow#4]
![image](https://user-images.githubusercontent.com/18388484/30572372-bfb09cfc-9d1f-11e7-9cf8-13a5f2e77fd8.png)
真的不应该是_blank么:-D

**Comment by lilijialiang** [comment]
@maoqxxmm 估计是开发君的手误，谢谢指正哈，已修复了。

客户端使用方面如有什么问题，也可以反馈到 issue 我们会第一时间反馈哈。
