### ISSUE TITLE
打不开以下磁盘映像 破坏的映像

### ISSUE THREAD

**Issue by linqiang007** [legoflow/legoflow#5]
mac版的，不管哪里下载的都是这样的。

![image](https://user-images.githubusercontent.com/12245095/30684591-6e5cf000-9ee4-11e7-8b8d-1d32ff3c08ab.png)

**Comment by lilijialiang** [comment]
@linqiang007 目前还未遇到过这类情况，请问 macOS 系统版本是多少呢？

另外打了一个 app 的压缩包，可以在 [这里下载](https://pan.baidu.com/s/1ceynee)。

下载完成后，解压，直接拖进 <应用程序> 文件夹下，双击打开就可以了。

**Comment by linqiang007** [comment]
@lilijialiang 版本是10.10.5

**Comment by lilijialiang** [comment]
@linqiang007 可以下载上述 app 压缩包，解压，直接拖进 <应用程序> 文件夹下，双击打开。
