### ISSUE TITLE
怎么配置代理，我复制vue配置代理进去根本不行

### ISSUE THREAD

**Issue by fengweiqi** [legoflow/legoflow#9]
proxyTable: {

        '/web': {

            target: 'http://xxx.aa.cn',

            changeOrigin: true,

            pathRewrite: {
              '^/web': '/web'
            }
        }
    },

**Comment by lilijialiang** [comment]
@fengweiqi 请问有没有了解过[文档](https://github.com/legoflow/legoflow/wiki/5.-配置-legoflow.json#-proxy)，或者详细说明一下需求？

**Comment by fengweiqi** [comment]
@lilijialiang 有啊，文档讲的不详细，我这样配置也不行：

**Comment by fengweiqi** [comment]
@lilijialiang 有啊，文档讲的不详细，我这样配置也不行：  "proxy": {
        "^/web": "http://test.grtn.cn/web"
    },

**Comment by fengweiqi** [comment]
@lilijialiang 有啊，文档讲的不详细，我这样配置也不行： 
"proxy": {
"^/web": "http://xx.aa.cn/web"
},

**Comment by fengweiqi** [comment]
@lilijialiang  比如这样一个接口：http://xx.aa.cn/web/mobile/api/queryOtherInfo，在代码里面接口地址写的是：/web/mobile/api/queryOtherInfo，需求是要把localhost:3000/web/mobile/api/queryOtherInfo代理到http://xx.aa.cn/web/mobile/api/queryOtherInfo

**Comment by lilijialiang** [comment]
@fengweiqi 这个属于一个 Feature，今天已更新了内测版本 [v1.0.50](https://legoflow.com/changelog) 支持 **代理其他域的接口** 的功能，不久就会发布正式版本，若想先更新到内测版本，可以通过 [辅助工具](https://legoflow.com/util) 进行更新，谢谢你的建议。

**Comment by fengweiqi** [comment]
@lilijialiang 内测版本legoflow.json proxy字段格式怎么写呢

**Comment by lilijialiang** [comment]
@fengweiqi 

```js
"proxy": {
    "/mock": "http://legox.yy.com/mock/api/14",
},
```

[文档](https://github.com/legoflow/legoflow/wiki/5.-配置-legoflow.json#-proxy)   上已补充使用方式以及 DEMO 地址。

**Comment by fengweiqi** [comment]
@lilijialiang 你这个是匹配整个地址，没有vue配置文件那样匹配到/api时就代理到外域去吗

**Comment by fengweiqi** [comment]
@lilijialiang 你这个是匹配整个地址，没有vue配置文件那样匹配到/api时就代理到外域去吗，像这样，/api开头，会代理到：http://aa.xx.com/api上去，比如：localhost:3000/api/user/id/3会代理到http://aa.xx.com/api/user/3上去，但配置文件根本不需要写整个接口地址
proxyTable: {

    '/web': {


        target: 'http://xxx.aa.cn',

        changeOrigin: true,

        pathRewrite: {
          '^/web': '/web'
        }
    }
},

**Comment by fengweiqi** [comment]
@lilijialiang 你这个是匹配整个地址，没有vue配置文件那样匹配到/api时就代理到外域去吗，像这样，/api开头，会代理到：http://xxx.aa.cn/api上去，比如：localhost:3000/api/user/id/3会代理到http://aa.xx.com/api/user/3上去，但配置文件根本不需要写整个接口地址
proxyTable: {

'/web': {


    target: 'http://xxx.aa.cn',

    changeOrigin: true,

    pathRewrite: {
      '^/api': '/api'
    }
}
},

**Comment by lilijialiang** [comment]
@fengweiqi 这个是 Feature 的基本需求的，后面还在加上匹配路径代理，例如：

```js
proxy: {
    '/api/**': 'http://a.com/api/**'
}
```

**Comment by lilijialiang** [comment]
版本 1.0.51  已支持 **代理某个接口** 或 **代理某个域**。

**Comment by fengweiqi** [comment]
@lilijialiang 你这个还是不行呀，代理只能写完整的接口地址，而且还没办法把参数传过去[\冷汗]

**Comment by lilijialiang** [comment]
麻烦才把版本号，系统版本，贴一下。

测试过代理路径而不是完整 URL，或者在群里发一下你的测试 DEMO ？
